%% Assessment: Evaluate all calculator expressions.
assert(isequaln(powerValues, referenceVariables.powerValues), ...
    "powerValues does not match the reference result.")
assert(isequaln(imaginaryRoot, referenceVariables.imaginaryRoot), ...
    "imaginaryRoot does not match the reference result.")
assert(isequaln(eValue, referenceVariables.eValue), ...
    "eValue does not match the reference result.")
assert(isequaln(radianCosine, referenceVariables.radianCosine), ...
    "radianCosine does not match the reference result.")
assert(isequaln(degreeCosine, referenceVariables.degreeCosine), ...
    "degreeCosine does not match the reference result.")
